#Nmake /f Makefile     with ifort
#make -f Makefile      with gfortran
# Set the remove file command for your system
# Used in the clean command
rm = del

# Set the required Fortran compiler and associated flags
#f90comp= ifort
f90comp= gfortran

# name the executable
flag= -o       
# Set the compilation flags
# Optimize
switch= -O3 

# Set the extension for object files: obj for Windows, o for Linux
#O = obj
O = o

OBJS = set_rk.$O  FS_FC_Z_mod_rk.$O  
mod_mid= set_rk.mod  FS_FC_Z_mod_rk.mod
	
FS_FC_Z_Driver_rk: $(OBJS) FS_FC_Z_Driver_rk.$O
	$(f90comp) $(flag) FS_FC_Z_Driver_rk $(switch) $(OBJS)\
         FS_FC_Z_Driver_rk.$O 

set_rk.mod: set_rk.$O set_rk.f90
set_rk.$O: set_rk.f90
	$(f90comp) -c $(switch) set_rk.f90
FS_FC_Z_mod_rk.mod: FS_FC_Z_mod_rk.$O FS_FC_Z_mod_rk.f90
FS_FC_Z_mod_rk.$O: set_rk.$O 
	$(f90comp) -c $(switch) FS_FC_Z_mod_rk.f90
FS_FC_Z_Driver_rk.$O: FS_FC_Z_mod_rk.$O FS_FC_Z_Driver_rk.f90 set_rk.$O  
	$(f90comp) -c $(switch) FS_FC_Z_Driver_rk.f90

# Cleaning 
# remove all files generated by the compiler
# these are compiler dependent
clean:
	del -f *.$O *.d *.g90 *.mod *.exe
