! MODULE SET_RK PROVIDES THE KIND TYPE PARAMETER NEEDED TO DEFINE
! THE PRECISION OF A COMPLETE PACKAGE ALONG WITH VALUES
! FOR COMMONLY USED STANDARD PRECISIONS

module set_rk
Use ISO_FORTRAN_ENV, only :REAL32, REAL64, REAL128
    IMPLICIT NONE
    PUBLIC :: RK, SP, DP, QP
    
     ! PRECISIONS
    INTEGER, PARAMETER :: SP = REAL32   ! SINGLE PRECISION
    INTEGER, PARAMETER :: DP = REAL64   ! DOUBLE PRECISION
    INTEGER, PARAMETER :: QP = REAL128  ! QUADRUPLE PRECISION

    ! SET THE PRECISION FOR THE WHOLE PACKAGE
    INTEGER, PARAMETER :: RK = QP

    ! TO CHANGE THE DEFAULT PACKAGE-PRECISION CHANGE
    ! THE PARAMETER ASSIGNED TO RK ABOVE TO THE REQUIRED
    ! PRECISION AND RECOMPILE THE COMPLETE PACKAGE.

END MODULE SET_RK
